In [4]:
import numpy as np
list = [20,27,9,12,31,17,4,50,39,35]
arr = np.array(list)
print("original array:", arr)
arr_times4 = arr * 4
print("array multiplied by 4:", arr_times4)
mean_val = np.mean(arr)
print("mean", mean_val)
median_val = np.median(arr)
print("median", median_val)
std_val = np.std(arr)
print("standard deviation")
min_index = np.argmin(arr)
max_index = np.argmax(arr)
print("index of smallest value:", min_index)
print("index of largest value:", max_index)
print("smallest value from index:", arr[min_index])
print("largest value from index:", arr[max_index])
min_val = np.min(arr)
max_val = np.max(arr)
print("np.min() value:", min_val)
print("np.max() value:", max_val)
print("do they match:", (min_val == arr[min_index]) and (max_val == arr[max_index]))
greater_than_20 = arr[arr > 20]
print("values greater than 20:", greater_than_20)

original array: [20 27  9 12 31 17  4 50 39 35]
array multiplied by 4: [ 80 108  36  48 124  68  16 200 156 140]
mean 24.4
median 23.5
standard deviation
index of smallest value: 6
index of largest value: 7
smallest value from index: 4
largest value from index: 50
np.min() value: 4
np.max() value: 50
do they match: True
values greater than 20: [27 31 50 39 35]


In [8]:
import numpy as np
matrix = np.array([[5,12,17,9],[8, 21, 14, 3],[6, 13, 19, 11]])
print("shape:", matrix.shape)
print("rows:", matrix.shape[0])
print("columns:", matrix.shape[1])
print("third column:", matrix[:,2])
print("second row:", matrix[1])
print("matrix x2:", matrix*2)
print("column means:", np.mean(matrix, axis = 0))
print("overall mean:", np.mean(matrix))
print("row maxes:", np.max(matrix, axis=1))
print("column mins:", np.min(matrix, axis=0))
flat = matrix.flatten()
print("flattened array:", flat)
print("new shape:", flat.shape)
min_index = np.argmin(flat)
max_index = np.argmax(flat)
print("flat index of min:", min_index)
print("flat index of max:", max_index)
min_coords = np.unravel_index(min_index, matrix.shape)
max_coords = np.unravel_index(max_index, matrix.shape)
print("min coords:", min_coords)
print("max coords:", max_coords)
greater_than_15 = matrix[matrix > 15]
print("values > 15:", greater_than_15)
sorted_matrix = np.sort(matrix, axis=1)
print("row sorted matrix:", sorted_matrix)

shape: (3, 4)
rows: 3
columns: 4
third column: [17 14 19]
second row: [ 8 21 14  3]
matrix x2: [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
column means: [ 6.33333333 15.33333333 16.66666667  7.66666667]
overall mean: 11.5
row maxes: [17 21 19]
column mins: [ 5 12 14  3]
flattened array: [ 5 12 17  9  8 21 14  3  6 13 19 11]
new shape: (12,)
flat index of min: 7
flat index of max: 5
min coords: (np.int64(1), np.int64(3))
max coords: (np.int64(1), np.int64(1))
values > 15: [17 21 19]
row sorted matrix: [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [11]:
import numpy as np
def is_prime(n):
    if n<2:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True
def rows_with_primes(arr):
    result = []
    for row in arr:
        if any(is_prime(val) for val in row):
            result.append(row)
    return np.array(result)
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])
filtered = rows_with_primes(arr)
print(filtered)

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [12]:
import numpy as np
def checkerboard():
    board = np.zeros((8,8), dtype=int)
    for i in range(8):
        if i % 2 == 0:
            board[i] = [1 if j % 2 == 0 else 0 for j in range(8)]
        else:
            board[i] = [0 if j % 2 == 0 else 1 for j in range(8)]
    return board
print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [13]:
import numpy as np
def reverse_checkerboard():
    board = np.zeros((8,8), dtype=int)
    for i in range(8):
        if i % 2 == 0:
            board[i] = [0 if j % 2 == 0 else 1 for j in range(8)]
        else:
            board[i] = [1 if j % 2 == 0 else 0 for j in range(8)]
    return board
print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
import numpy as np
def expansion(arr, num_space):
    spacer = ' ' * num_space
    return np.array([spacer.join(str(word)) for word in arr])
universe = np.array(['galaxy','clusters'])
print(expansion(universe, 1))
print(expansion(universe, 2))

['g a l a x y' 'c l u s t e r s']
['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [22]:
import numpy as np
def seconddimmest(arr):
    return np.sort(arr, axis=1)[:, -2]
np.random.seed(123)
stars = np.random.randint(500,2000, (5,5))
print("star clusters:", stars)
print("second brightest stars:", seconddimmest(stars))

star clusters: [[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
second brightest stars: [1889 1647 1138 1863 1592]
